CREATE TABLE IF NOT EXISTS Usuario (
   UserId SERIAL PRIMARY KEY,
   FirstName VARCHAR(150) NOT NULL,
   LastName VARCHAR(150) NOT NULL,
   UserName VARCHAR(50) NOT NULL,
   Password VARCHAR(10) NOT NULL
);